# Generated by Django 3.2.7 on 2021-10-01 08:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tractor_price', models.IntegerField(max_length=150)),
                ('implimentaion', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('tractor_company', models.CharField(max_length=50)),
                ('tractor_model', models.CharField(max_length=50)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tractor.farmer')),
            ],
        ),
    ]
