# Generated by Django 3.2.7 on 2021-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
