# Generated by Django 3.2.7 on 2021-10-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0003_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
    ]
