# Generated by Django 3.2.7 on 2021-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0005_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
